### ISSUE TITLE
const { color } = __vite_ssr_import_0__.default;

### ISSUE THREAD

**Issue by Aj-Butt** [askrella/whatsapp-chatgpt#290] opened 2023-08-25 09:22 UTC
PS C:\Users\Aj\Pictures\whatsapp-gpt-mobilink> npm run start

> whatsapp-chatgpt@1.0.0 start
> npx vite-node src/index.ts

(node:27624) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
const { color } = __vite_ssr_import_0__.default;

TypeError: Cannot destructure property 'color' of '__vite_ssr_import_0__.default' as it is undefined.
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\callbacks\handlers\console.js:25:9
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\callbacks\manager.js:3:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\llms\base.js:4:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)
    at C:\Users\Aj\Pictures\whatsapp-gpt-mobilink\node_modules\langchain\dist\llms\index.js:1:31
    at ViteNodeRunner.directRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:328:5)
    at ViteNodeRunner.cachedRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:186:14)
    at ViteNodeRunner.dependencyRequest (file:///C:/Users/Aj/Pictures/whatsapp-gpt-mobilink/node_modules/vite-node/dist/client.mjs:221:12)

**Comment by choudhryfrompak** [comment] 2023-08-27 16:13
did you found solution?

**Comment by Aj-Butt** [comment] 2023-08-28 10:04
no

**Comment by laputa714** [comment] 2023-09-25 15:24
same issue here . anyone have solution ? try to debug but fail....

**Comment by bamit99** [comment] 2023-09-26 10:42
Initially it was strict error and now this.

**Comment by Isaakkamau** [comment] 2023-09-28 15:24
Hello guys this error is being caused by compatibility between node and npm. This has worked for me
`npm install -g npm@9` 
I have `Node.js v19.9.0` installed

**Comment by navopw** [comment] 2023-10-01 12:37
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!

**Closed by navopw** 2023-10-01 12:37 UTC
