### ISSUE TITLE
vite node error 

### ISSUE THREAD

**Issue by shandhiviyarajan** [askrella/whatsapp-chatgpt#254] opened 2023-06-08 10:08 UTC
> npx vite-node src/index.ts

file:///Users/user/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53776
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: /Users/user/Desktop/projects/whatsapp-chatgpt-master/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///Users/user/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53776:15)
    at ssrTransform (file:///Users/user/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53751:12)
    at Object.ssrTransform (file:///Users/user/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63307:20)
    at loadAndTransform (file:///Users/user/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53422:24)

**Comment by elwizard33** [comment] 2023-06-10 18:38
I did a manual fix by replacing the QR black and white in this file /whatsapp-chatgpt-master/node_modules/qrcode-terminal/lib/main.js

From:
    black = "\033[40m  \033[0m",
    white = "\033[47m  \033[0m",

To:
    black = "\x1b[40m  \x1b[0m",
    white = "\x1b[47m  \x1b[0m",
    
However, I don’t think this is the cleanest approach, I noticed there are some newer versions of the dependencies from this project, so I'm working on some of those updates to see if there are any breaking changes.

But if you're testing this should help you get started.

**Comment by witchfindertr** [comment] 2023-06-11 20:34
Need to install the following packages:
  vite-node@0.32.0
Ok to proceed? (y) y
file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53776
        throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
              ^

Error: Parse failure: Octal literal in strict mode (3:13)
At file: C:/Users/Administrator/Desktop/gonder/m/node_modules/qrcode-terminal/lib/main.js
Contents of line 3:     black = "\033[40m  \033[0m",
    at ssrTransformScript (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53776:15)
    at ssrTransform (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53751:12)
    at Object.ssrTransform (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:63307:20)
    at loadAndTransform (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53422:24)

Node.js v18.16.0

**Comment by leoliew** [comment] 2023-06-13 04:10
npm install vite-node@0.31.1

**Comment by jorgehen** [comment] 2023-06-17 10:43
> `npm install vite-node@0.31.1` Specify the version when installing vite-node

it worked for me

**Comment by apfordz** [comment] 2023-07-20 11:16
It fixed my issue thanks

**Comment by kingofkillers91** [comment] 2023-07-23 14:48
Hi guys, this is my current main.js: 
'use strict';
const QRCode = require('./../vendor/QRCode');
const QRErrorCorrectLevel = require('./../vendor/QRCode/QRErrorCorrectLevel');

const black = "\x1b[40m \x1b[0m";
const white = "\x1b[47m \x1b[0m";

function toCell(isBlack) {
    return isBlack ? black : white;
}

function repeat(color) {
    return {
        times: function (count) {
            return new Array(count).join(color);
        }
    };
}

function fill(length, value) {
    return new Array(length).fill(value);
}

module.exports = {
    error: QRErrorCorrectLevel.L,

    generate(input, opts, cb) {
        if (typeof opts === 'function') {
            cb = opts;
            opts = {};
        }

        const qrcode = new QRCode(-1, this.error);
        qrcode.addData(input);
        qrcode.make();

        let output = '';
        if (opts && opts.small) {
            const BLACK = true;
            const WHITE = false;
            const moduleCount = qrcode.getModuleCount();
            const moduleData = qrcode.modules.slice();
            const oddRow = moduleCount % 2 === 1;

            if (oddRow) {
                moduleData.push(fill(moduleCount, WHITE));
            }

            const platte = {
                WHITE_ALL: '\u2588',
                WHITE_BLACK: '\u2580',
                BLACK_WHITE: '\u2584',
                BLACK_ALL: ' ',
            };

            const borderTop = repeat(platte.BLACK_WHITE).times(moduleCount + 3);
            const borderBottom = repeat(platte.WHITE_BLACK).times(moduleCount + 3);
            output += borderTop + '\n';

            for (let row = 0; row < moduleCount; row += 2) {
                output += platte.WHITE_ALL;

                for (let col = 0; col < moduleCount; col++) {
                    if (moduleData[row][col] === WHITE && moduleData[row + 1][col] === WHITE) {
                        output += platte.WHITE_ALL;
                    } else if (moduleData[row][col] === WHITE && moduleData[row + 1][col] === BLACK) {
                        output += platte.WHITE_BLACK;
                    } else if (moduleData[row][col] === BLACK && moduleData[row + 1][col] === WHITE) {
                        output += platte.BLACK_WHITE;
                    } else {
                        output += platte.BLACK_ALL;
                    }
                }

                output += platte.WHITE_ALL + '\n';
            }

            if (!oddRow) {
                output += borderBottom;
            }
        } else {
            const border = repeat(white).times(qrcode.getModuleCount() + 3);

            output += border + '\n';
            qrcode.modules.forEach(function (row) {
                output += white;
                output += row.map(toCell).join('');
                output += white + '\n';
            });
            output += border;
        }

        if (cb) {
            cb(output);
        } else {
            console.log(output);
        }
    },

    setErrorLevel(error) {
        this.error = QRErrorCorrectLevel[error] || this.error;
    }
};

It's not working.
I eve tried to install = npm install vite-node@0.31.1

This is what i get: 

Attaching to whatsapp-chatgpt
whatsapp-chatgpt  | 
whatsapp-chatgpt  | > whatsapp-chatgpt@1.0.0 start
whatsapp-chatgpt  | > npx vite-node src/index.ts
whatsapp-chatgpt  | 
whatsapp-chatgpt  | 
whatsapp-chatgpt  | file:///app/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55271
whatsapp-chatgpt  |         throw new Error(`Parse failure: ${err.message}\nAt file: ${url}\nContents of line ${line}: ${code.split('\n')[line - 1]}`);
whatsapp-chatgpt  |               ^
whatsapp-chatgpt  | 
whatsapp-chatgpt  | Error: Parse failure: Octal literal in strict mode (3:13)
whatsapp-chatgpt  | At file: /app/node_modules/qrcode-terminal/lib/main.js
whatsapp-chatgpt  | Contents of line 3:     black = "\033[40m  \033[0m",
whatsapp-chatgpt  |     at ssrTransformScript (file:///app/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55271:15)
whatsapp-chatgpt  |     at ssrTransform (file:///app/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:55246:12)
whatsapp-chatgpt  |     at Object.ssrTransform (file:///app/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:64913:20)
whatsapp-chatgpt  |     at loadAndTransform (file:///app/node_modules/vite/dist/node/chunks/dep-a8e37fae.js:54917:24)
whatsapp-chatgpt  |     at ViteNodeServer._transformRequest (file:///app/node_modules/vite-node/dist/server.mjs:373:16)
whatsapp-chatgpt  |     at ViteNodeServer._fetchModule (file:///app/node_modules/vite-node/dist/server.mjs:340:17)
whatsapp-chatgpt  |     at ViteNodeRunner.directRequest (file:///app/node_modules/vite-node/dist/client.mjs:248:46)
whatsapp-chatgpt  |     at ViteNodeRunner.cachedRequest (file:///app/node_modules/vite-node/dist/client.mjs:197:14)
whatsapp-chatgpt  |     at ViteNodeRunner.dependencyRequest (file:///app/node_modules/vite-node/dist/client.mjs:231:12)
whatsapp-chatgpt  |     at /app/src/index.ts:1:31
whatsapp-chatgpt  | 
whatsapp-chatgpt  | Node.js v20.5.0
whatsapp-chatgpt  | 


Thanks

**Comment by jerryrat** [comment] 2023-08-03 06:42
> `npm install vite-node@0.31.1` Specify the version when installing vite-node

fixed，thank you

**Comment by sigittekno** [comment] 2023-08-11 02:01
C:\Users\adcwa\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'CallCollection')
    at __puppeteer_evaluation_script__:9:66
    at ExecutionContext._evaluateInternal (C:\Users\adcwa\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:273:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ExecutionContext.evaluate (C:\Users\adcwa\whatsapp-chatgpt\node_modules\whatsapp-web.js\node_modules\puppeteer\src\common\ExecutionContext.ts:140:12)
    at Client.initialize (C:\Users\adcwa\whatsapp-chatgpt\node_modules\whatsapp-web.js\src\Client.js:278:9)
    
    
    I GET MESSAGE HERE AFTER NOM INSTALL VITE-NODE@0.31.1

**Comment by cmastro** [comment] 2023-08-18 06:53
@sigittekno I have the same issue, and I fix it by removing `node_modules` folder and reinstalling:
- `npm install`
- `npm install vite-node@0.31.1`

**Comment by emrekaramannnn** [comment] 2023-08-30 11:44
![3](https://github.com/askrella/whatsapp-chatgpt/assets/127592314/69da01f3-47b5-4e66-9ef5-f3f133604dc8)

I followed all the steps and the problem is not fixed. Unable to start session.

**Comment by navopw** [comment] 2023-10-01 12:40
I fixed lots of issues. It currently works on my side.

I will close this PR for now. If you still have issues, please open another PR.

Thanks!

**Closed by navopw** 2023-10-01 12:40 UTC
